### ISSUE TITLE
Video Folder not show 

### ISSUE THREAD

**Issue by alokfuterox** [chiunam/CTAssetsPickerController#100]
Hi, 
Iphone "Video folder" Not show using CTAssetsPickerController

Regards
Alok

**Comment by chiunam** [comment]
Hi @alokfuterox, what do you mean of "Video folder"? It that shown in the demo app?

**Comment by chiunam** [comment]
Closed due to inactivity.

**Comment by krusek** [comment]
Here's what I'm getting.

In the Photos app:
![img_0169](https://cloud.githubusercontent.com/assets/1695965/8479514/271b9610-208d-11e5-9552-0592ca0d3459.jpg)


Using CTAssetsPickerController:
![img_0168](https://cloud.githubusercontent.com/assets/1695965/8479518/2b00ebf4-208d-11e5-99b2-9e3b38a9159f.jpg)


One of the dynamic folders is called "Videos" and I'm guessing that's what the @alokfuterox is talking about.

Does this require CTAssetsPickerController be updated to the newer Photos framework? If so is there a timeframe on that update?

**Comment by chiunam** [comment]
Refer to #117
