### ISSUE TITLE
Is it possible to only show the most recent photos on the Camera Roll?

### ISSUE THREAD

**Issue by drchris1502** [chiunam/CTAssetsPickerController#101]
In my implementation of CTAssetsPickerController, if there are a lot of photos in the Camera Roll (1954), the picker loads very slowly, without a progress indicator and so my app appears to have frozen.  Is it possible to speed this up by specifying only to show the most recent 100 photos (for example) in an asset group?

Thanks!
Chris

**Comment by chiunam** [comment]
Hi @drchris1502, no such feature is implemented but you can disable assets by returning `No` in `shouldShowAsset:` delegate method.
