### ISSUE TITLE
[Feature Request] Show photo selection order

### ISSUE THREAD

**Issue by tomoyuki28jp** [chiunam/CTAssetsPickerController#102]
like this https://github.com/mikaoj/BSImagePicker

**Comment by chiunam** [comment]
Hi @tomoyuki28jp. I'm currently working on the next major release that would support Photos framework. Will try to look into this suggestion afterward. Thank you.

**Comment by tomoyuki28jp** [comment]
Glad to hear that! Thanks for your reply @chiunam :)

**Comment by tomoyuki28jp** [comment]
@chiunam Thanks a lot!

**Comment by chiunam** [comment]
@tomoyuki28jp hope you like this look-and-feel. It is actually brought from Facebook app.

**Comment by tomoyuki28jp** [comment]
@chiunam Works as expected! Thanks :)
