### ISSUE TITLE
can I use it in a non-cocoapods project?

### ISSUE THREAD

**Issue by ximmyxiao** [chiunam/CTAssetsPickerController#105]
seems crashed without a CTAssetsPickerController.bundle, thx

**Comment by chiunam** [comment]
@ximmyxiao You can build the bundle by running the script mentioned in [SUBMODULES-NOTES](https://github.com/chiunam/CTAssetsPickerController/blob/master/SUBMODULES-NOTES.md)

The cocoapods is still recommended. Coming major release might drop support for non-cocoapods projects.
