### ISSUE TITLE
create_bundle error when we do git submodule

### ISSUE THREAD

**Issue by jiangyancong** [chiunam/CTAssetsPickerController#107]
Hi,chiunam

I follow the SUBMODULES-NOTES.md
guide to integrate CTAssetsPicker into my project.
But I met an error in create_bundle. Please have a look and let me know how to fix the issue or create bundle in other way. Thank you very much.
CTAssetsPickerController$ ls
CTAssetsPickerController		README.md
CTAssetsPickerController.podspec	RELEASE-NOTES.md
CTAssetsPickerDemo			Resources
CTAssetsPickerDemo.xcodeproj		SUBMODULES-NOTES.md
CTAssetsPickerDemo.xcworkspace		Screenshot.png
LICENSE					create_bundle
Podfile
CTAssetsPickerController$ ./create_bundle 
./create_bundle:21:in `eval': undefined method `version' for #<Pod::Spec:0x007fee8a8332b0> (NoMethodError)
	from (eval):18:in `block in <main>'
	from ./create_bundle:11:in `initialize'
	from (eval):1:in `new'
	from (eval):1:in `<main>'
	from ./create_bundle:21:in `eval'
	from ./create_bundle:21:in `<main>'
CTAssetsPickerController$

**Comment by chiunam** [comment]
@jiangyancong I've updated the cocopodspec file and it should be working now.
