### ISSUE TITLE
Allow selection on preview

### ISSUE THREAD

**Issue by pushtheworldllc** [chiunam/CTAssetsPickerController#111]
Two feature requests:
1) On the full screen preview screen have the ability to select/deselect photos
2) Tell user about long press with tutorial like popup

**Comment by chiunam** [comment]
Hi @pushtheworldllc 

1) Many people had requested such feature. As the preview screen (`CTAssetsPageViewController`) might be reused for viewing assets, I have to find a proper way to make it more customisable first.

2) Tutorial like popup might not be good as a custom control. You might consider to show such tutorial before presenting the picker.
