### ISSUE TITLE
picker will always be created when clicked addButton.It Will cause leakage

### ISSUE THREAD

**Issue by guakeliao** [chiunam/CTAssetsPickerController#112]
In your demo picker will always be created when clicked addButton.It Will cause leakage.
   But if I use @property(nonatomic, strong) CTAssetsPickerController *picker;,  this CTAssetsViewController collectionView  don't reloadData.

**Comment by chiunam** [comment]
@guakeliao I don't get it. When you dismiss the picker, it should be released automatically. That's common practices to present view controller with ARC.

**Comment by chiunam** [comment]
Closed due to inactivity.
