### ISSUE TITLE
Appearance customization

### ISSUE THREAD

**Issue by Remyoman** [chiunam/CTAssetsPickerController#113]
Changing the navigationcontroller properties is quite easy and well documented.For the other views (collection, album selection) we have to use the UIAppearance protocol and the official documentation is referenced. The process for changing the appearance for these views is complex due to their containment, making the process tedious and very much trial and error.

Would it be possible to give more concrete examples for customizing the appearance of the cells and other views used in this picker? Besides UIAppearance customization, more control or access to the appearance properties of the used cells and views would also be helpful if at all possible.

**Comment by chiunam** [comment]
@Remyoman There's would be a more detailed sample for customising in the coming major release. Stay tuned.

**Comment by chiunam** [comment]
Added in the [v3.0.0-beta.1](9301ee2df72a3cd75648eef525f11af35623ebe6)
