### ISSUE TITLE
NSInvalidArgumentException when running example in simulator

### ISSUE THREAD

**Issue by demiantres** [chiunam/CTAssetsPickerController#116]
Hi, 

When I try to run the example project in the iOS simulator (8.2) I get this error:

CTAssetsPickerDemo[89250:1657430] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010c08ba75 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010bd24bb7 objc_exception_throw + 45
	2   CoreFoundation                      0x000000010c08b9ad +[NSException raise:format:] + 205
	3   Foundation                          0x000000010b894aa2 -[NSPlaceholderString initWithFormat:locale:arguments:] + 115
	4   Foundation                          0x000000010b898068 +[NSString stringWithFormat:] + 174
	5   CTAssetsPickerDemo                  0x0000000109ebbf78 -[CTAssetsSupplementaryView bind:] + 536
	6   CTAssetsPickerDemo                  0x0000000109ec065f -[CTAssetsViewController collectionView:viewForSupplementaryElementOfKind:atIndexPath:] + 223
	7   UIKit                               0x000000010abec53a -[UICollectionView _createPreparedSupplementaryViewForElementOfKind:atIndexPath:withLayoutAttributes:applyAttributes:] + 449
	8   UIKit                               0x000000010abed70a -[UICollectionView _updateVisibleCellsNow:] + 3483
	9   UIKit                               0x000000010abee8f1 -[UICollectionView _updateVisibleCellsNow:] + 8066
	10  UIKit                               0x000000010abf1391 -[UICollectionView layoutSubviews] + 243
	11  UIKit                               0x000000010a6361c3 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 521
	12  QuartzCore                          0x000000010cef8c58 -[CALayer layoutSublayers] + 150
	13  QuartzCore                          0x000000010ceed87e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 380
	14  QuartzCore                          0x000000010ceed6ee _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	15  QuartzCore                          0x000000010ce5b36e _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 242
	16  QuartzCore                          0x000000010ce5c482 _ZN2CA11Transaction6commitEv + 390
	17  QuartzCore                          0x000000010ce5caed _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 89
	18  CoreFoundation                      0x000000010bfc0507 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	19  CoreFoundation                      0x000000010bfc0460 __CFRunLoopDoObservers + 368
	20  CoreFoundation                      0x000000010bfb6293 __CFRunLoopRun + 1123
	21  CoreFoundation                      0x000000010bfb5bc6 CFRunLoopRunSpecific + 470
	22  GraphicsServices                    0x000000010ca2fa58 GSEventRunModal + 161
	23  UIKit                               0x000000010a5bc580 UIApplicationMain + 1282
	24  CTAssetsPickerDemo                  0x0000000109ebb853 main + 115
	25  libdyld.dylib                       0x000000010ee51145 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by jneiluj** [comment]
Please check you created the bundle: https://github.com/chiunam/CTAssetsPickerController/wiki/Manual-Setup-(v3)

**Comment by chiunam** [comment]
@jneiluj Thanks for your help.
@demiantres You might also need to run `pod install`: https://github.com/chiunam/CTAssetsPickerController/wiki/Running-demo-app
