### ISSUE TITLE
Dynamic folders not showing

### ISSUE THREAD

**Issue by krusek** [chiunam/CTAssetsPickerController#117]
Here's what I'm getting.

In the Photos app:
![img_0169](https://cloud.githubusercontent.com/assets/1695965/8479514/271b9610-208d-11e5-9552-0592ca0d3459.jpg)

Using CTAssetsPickerController:
![img_0168](https://cloud.githubusercontent.com/assets/1695965/8479518/2b00ebf4-208d-11e5-99b2-9e3b38a9159f.jpg)

One of the dynamic folders is called "Videos" and I'm guessing that's what the @alokfuterox is talking about.

Does this require CTAssetsPickerController be updated to the newer Photos framework? If so is there a timeframe on that update?

I'm also having some users report that lots of images aren't showing in my app. Like they have screenshots where the Photos app shows 500 photos but CTAssetsPickerController only shows 100 or so. Maybe it's iCloud photos not showing?

**Comment by chiunam** [comment]
@krusek Yes. The issues are due to the limitation of the ALAsset framework. The Photos framework version has just released for [beta testing](https://github.com/chiunam/CTAssetsPickerController/tree/v3). Please try and feedback

**Comment by krusek** [comment]
This beta version will require iOS 8, correct? that is, it won't fall back to ALAsset framework for iOS 7? And I can't have both versions at once?

**Comment by chiunam** [comment]
Yes. It won't fall back to ALAsset framework. Future released versions will only support Photos framework too. As Photos framework is not compatible to ALAsset framework, it is probably not able to include both versions at once.
