### ISSUE TITLE
v3 translations

### ISSUE THREAD

**Issue by chiunam** [chiunam/CTAssetsPickerController#118]
Hi to all localisation contributors,

CTAssetsPickerController is just released the [v3.0.0](https://github.com/chiunam/CTAssetsPickerController/tree/v3) for beta testing (finally!). As there are two new strings (actually just one, another is the OK button) for displaying error message of playing stream video, I would like to seek your help for translating them to the localisations you submitted before. 

The message is copied from Photos.app and it will be shown when `PHImageManager` try to load the video from iCloud but fail. Please see below the message from Photos.app for your reference.

![ctassetspicker_stream_video_error](https://cloud.githubusercontent.com/assets/327273/8664228/fb6aef2e-2a06-11e5-90e0-478a0b315ad1.png)

You might also add new localisations as you wish, just be reminded that you have to add the new translation to the LaunchScreen.xib in the demo app in order to make it work.  (I'm not sure the reasons behind but if there are no files in the demo app bundle got translated then the translation won't be shown, even the pod has that translations.)

Please submit the changes via PR as usual. Thank you.

CC @cabeca, @jneiluj, @georgschlenkhoff, @LMVogel, @sadiq81, @tomoyuki28jp, @binattori, @sztoth, @MarshalGeazipp, @Remyoman

**Comment by tmht** [comment]
@chiunam "Stream Video" is different from a normal video?

**Comment by tomoyuki28jp** [comment]
@chiunam "Stream Video" is different from a normal video?

**Comment by chiunam** [comment]
@tomoyuki28jp Yes. "Stream Video" is videos stored in iCloud.
