### ISSUE TITLE
Increase customization options.

### ISSUE THREAD

**Issue by Remyoman** [chiunam/CTAssetsPickerController#126]
It would be nice to have even more customization in addition to the new options that 3.0.0 brings. The current component is really great to work with, but I can see some places where more customization is possible and would be nice to have.

A number of things that would be nice to have:
- Borders for selected items (color, width).
- Background color for the grid view.
- Grid view spacing.
- Grid view cells per row.
- Custom checkmark image or even view.

I am willing to contribute and work on these changes, but I am not that known with the code base and the style that is maintained. Technical things can be discussed through pull requests I assume?

**Comment by chiunam** [comment]
@Remyoman Thanks for your suggestion. All PRs and discussions are welcome. 

BTW, currently it supports custom grid view spacing and cells per row can by custom collection view layout.
