### ISSUE TITLE
crash when i begin select photos

### ISSUE THREAD

**Issue by cloudPig** [chiunam/CTAssetsPickerController#129]
![image](https://cloud.githubusercontent.com/assets/8436462/8875424/b4137180-324b-11e5-86ec-b2ba2a68b1ba.png)

and log this

2015-07-24 21:31:23.110 FingerTips[10041:2258182] NSScanner: nil string argument
2015-07-24 21:31:23.110 FingerTips[10041:2258182] NSScanner: nil string argument
libc++abi.dylib: terminate_handler unexpectedly threw an exception

how can i fix this

**Comment by arik-so** [comment]
Yes, the same issue happens to me, as well.

**Comment by chiunam** [comment]
If you add the project manually, you have to run the `create_bundle` script as described in [wiki](https://github.com/chiunam/CTAssetsPickerController/wiki/Manual-Setup-(v3)).

**Comment by arik-so** [comment]
No, the project was added using CocoaPods.

**Comment by chiunam** [comment]
Please try v3.0.2 and see whether it fixes your issue. Thank you.

**Comment by tomoyuki28jp** [comment]
I might have the same issue with CTAssetsPickerController (3.0.3) installed via cocoapods with use_frameworks!. Xcode version is 6.4.

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[PHAsset thumbnail]: unrecognized selector sent to instance 0x1743b2600'
*** First throw call stack:
(0x181d1822c 0x1939e40e4 0x181d1f2f4 0x181d1c0a8 0x181c1e96c 0x1000de7f0 0x1000ddff4 0x1000de0c4 0x100726688 0x1867c91ec 0x1867c91ec 0x1867b22c8 0x1867c8b88 0x1867c8814 0x1867c1d50 0x186794f74 0x186a36124 0x186793488 0x181ccff8c 0x181ccf230 0x181ccd2e0 0x181bf8f74 0x18b6536fc 0x1867fad94 0x1000a71f4 0x19408ea08)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by tomoyuki28jp** [comment]
(Sorry, I deleted my previous comment which seems unrelated to this issue.)

**Comment by chiunam** [comment]
Closed due to inactivity.
