### ISSUE TITLE
Want to Limit the Photo selection

### ISSUE THREAD

**Issue by hassan31** [chiunam/CTAssetsPickerController#132]
Hello everyone, 
Is there any way to limit the selection of Photos in this pickerviewcontroller?
Like I want to select 3 photos only from this pickerViewController.

Thanks
Hassan

**Comment by chiunam** [comment]
@hassan31 Check the [demo app](https://github.com/chiunam/CTAssetsPickerController/wiki/Running-demo-app). There is an example showing what you are exactly looking for.

**Comment by hassan31** [comment]
Yes, I've already checked, but there is no option to limit the selection in the code.. As I can select as many as we can.

**Comment by chiunam** [comment]
Have you checked the example "Maximum selection"? You have to implement the `shouldSelectAsset` delegate.

**Comment by hassan31** [comment]
No, I didn't. Thanks I'll check it now.
One thing more, when I select the images from AssetPicker, and go back or press done button on navigation bar, then I've the main Album View Controller which have also done and cancel buttons on navigation bar. when I press both of them, id does not dismiss the the ViewController instead teh app hangs.

Any idea?

**Comment by nileshpol18** [comment]
```
func assetsPickerController(picker: CTAssetsPickerController!, shouldSelectAsset asset: PHAsset!) -> Bool {

    return picker.selectedAssets.count < 5 ? true : false
}
```
