### ISSUE TITLE
Navigation back pressed

### ISSUE THREAD

**Issue by freakafk** [chiunam/CTAssetsPickerController#133]
Hi,

When pressing back navigation button (Photos) with or without selecting image(s) freezes the app. Processor goes to 100% and need to kill the app.

I'm using iOS 6.4 for testing and this occurs on iPhone simulator and real device (iPhone 6/iOS 8.4).

Can you please point me to the right direction?

Thank you,
Vlad

**Comment by Dids** [comment]
+1

Also just noticed this, no idea what's causing it. Easily reproducible.

**Comment by Remyoman** [comment]
+1

Happens when I go back and then press cancel, otherwise it dismissed as usual.

**Comment by Dids** [comment]
I do recall this working the last time I used it, which was 3-4 days ago, meaning that the last commit(s) might've broken it.

**Comment by Dids** [comment]
I can confirm that reverting back to v3.0.0 "fixes" the issue, so for now, just downgrade until this gets fixed.

**Comment by chiunam** [comment]
Thanks for all reporting this issue. Will put it in first priority. In the meanwhile, please fallback to v3.0.0 as suggested by Dids.

**Comment by freakafk** [comment]
Thank you for your prompt response!

**Comment by chiunam** [comment]
This commit, f82fca52ce51788e70f91b5b7c47e6044463d954, introduced captioned issue. I have no clue why it freeze the app. I might need more time for fixing it.

**Comment by chiunam** [comment]
Found a proper way. Please update to v3.0.2.

**Comment by Dids** [comment]
Can confirm that this is indeed fixed, thank you!

**Comment by chiunam** [comment]
That's good.
