### ISSUE TITLE
iPad view not showing correctly

### ISSUE THREAD

**Issue by danshim** [chiunam/CTAssetsPickerController#134]
Hi,

It works great on iPhone, but when running on iPad, the screen looks blank.
![ios simulator screen shot aug 15 2015 7 58 58 pm](https://cloud.githubusercontent.com/assets/1028699/9291776/1b02cff6-4388-11e5-896c-6109ba6e0b07.png)

**Comment by chiunam** [comment]
#136 fixes this issue.
