### ISSUE TITLE
Is there a way to exclude iCloud photos?

### ISSUE THREAD

**Issue by somethingkindawierd** [chiunam/CTAssetsPickerController#138]
The new 3.0.* version includes support for iCloud photos. However, I cannot find way to exclude all images in iCloud. Is there a way to do this?

I’d like to configure it so only images actually on the device are viewable/selectable, if this is possible.

**Comment by chiunam** [comment]
Hi @somethingkindawierd,

That's probably feasible in iOS 9. According to Apples's `PHFetchOptions` [documentation](https://developer.apple.com/library/prerelease/ios/documentation/Photos/Reference/PHFetchOptions_Class/index.html#//apple_ref/occ/instp/PHFetchOptions/includeAssetSourceTypes), you can create a PHFetchOptions class which include the sources not from iCloud and then assign it to the `assetsFetchOptions` property of the picker.

**Comment by marijnschilling** [comment]
The assetSourceType `TypeCloudShared` only applies for assets that originate from an iCloud Shared Album. So that doesn't exclude your own photo's that are saved in the cloud.
