### ISSUE TITLE
Swift project: Cannot remove an observer <CTAssetsPickerController 0x7f94862ad530>

### ISSUE THREAD

**Issue by DeepDiving2015** [chiunam/CTAssetsPickerController#139]
hi,
I got this issue when use CTAssetsPickerController in my swift project:

Everything is ok when I open view and pick images. But when I back to the previous view without open CTAssetsPicker view, just crashed with: 
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CTAssetsPickerController 0x7f94862ad530> for the key path "selectedAssets" from <CTAssetsPickerController 0x7f94862ad530> because it is not registered as an observer.'

please confirm following code:

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self setupViews];
    [self setupEmptyViewController];
    [self checkAuthorizationStatus];
    [self addKeyValueObserver];         --->here to add
}

- (void)dealloc
{
    [self removeKeyValueObserver];    ---> should remove in "viewWillDisapear" instead of here??
}

**Comment by tomoyuki28jp** [comment]
I get the same error when I upgrade my project from xcode6.2 to xcode6.4 (swift1.2).

```
*** Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <CTAssetsPickerController 0x134240e40> for the key path "selectedAssets" from <CTAssetsPickerController 0x134240e40> because it is not registered as an observer.'
```

**Comment by tomoyuki28jp** [comment]
For the quick fix, adding try-catch block prevents app to crash.
https://github.com/tomoyuki28jp/CTAssetsPickerController/commit/0540a7af22b7e04f646d4d268aa09a50e0863cb9

**Comment by chiunam** [comment]
@tomoyuki28jp Thanks for your PR but I need time to review and hope to find a root cause of it first.

**Comment by tomoyuki28jp** [comment]
@chiunam Thanks for your reply. I haven't created a PR yet. If you need one, please let me know :)

**Comment by chiunam** [comment]
Hi @DeepDiving2015 and @tomoyuki28jp, may I know if this problem is still exist in Xcode 7 GM? As I have no swift projects on hand, I cannot verify the issue and make subsequence changes.

Moving `removeKeyValueObserver` to `viewWillDisappear` does not look proper to me as I always put such adding/removing code in load/dealloc or appear/disappear pair.

**Comment by DeepDiving2015** [comment]
@chiunam , I have not upgrade to Xcode 7 GM yet. 
Temporarily, I add a flag to mark KeyValueObserver is added, and use it when remove.

**Comment by tomoyuki28jp** [comment]
@chiunam I confirm this problem still exists in iOS9 (Xcode7).

**Comment by chiunam** [comment]
Hi @DeepDiving2015 & @tomoyuki28jp, this issue will be fixed in the next release.

**Comment by tomoyuki28jp** [comment]
@chiunam Thanks!!
