### ISSUE TITLE
Asset is null (iCloud)

### ISSUE THREAD

**Issue by Dids** [chiunam/CTAssetsPickerController#141]
I'm using this library for importing videos, and before I begin importing, I'm checking that the asset is not nil.

Now it would seem like that CTAssetsPickerController is unable to import videos that are older and most likely stored in iCloud and not necessarily on the device. It's showing them as selectable though, so I would assume that they would be on the device, but every attempt to import an older video (1-2 weeks or older) results in a null asset. No errors, no nothing.

Any clues on what could be causing this? This is kind of a deal breaker. :/

**Comment by Dids** [comment]
It would seem like the asset is null in PHImageManager when requesting the AVAsset.

**Comment by Dids** [comment]
Okay, I can definitely confirm that the videos in question are stored in iCloud instead of on device, as when I open them in Photos, I see a small loading circle in the lower right corner.

Now, can CTAssetsPickerController either hide files that haven't been loaded, or initiate the loading when they're selected?

**Comment by Dids** [comment]
Got it!

Before you can request the asset, you need to allow network access, like so:
```objc
PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
options.networkAccessAllowed = YES;
[[PHImageManager defaultManager] requestAVAssetForVideo:asset options:options resultHandler:^(AVAsset *asset, AVAudioMix *audioMix, NSDictionary *info)
{
    ...
}];
```

**Comment by chiunam** [comment]
@Dids Yes. Just read from Apple's document and found that there will be an option in iOS 9 for disabling iCloud assets for `PHImageManager`. It has also been mentioned in #138.

**Comment by Dids** [comment]
Since iOS is in charge of which assets are on the device and which ones are only available on iCloud, I don't think it would make much sense to disable iCloud assets, at least not if using the iCloud Library.

Downloading the assets is relatively snappy and straightforward, but it does lack any kind of user-facing progress indicators, and with large videos it can easily take a minute or two to download the assets.

I guess it would be nice a nice addition if CTAssetsPickerController had built-in support for downloading the assets from iCloud on it's own.

Oh and for anyone else looking for a solution, you can hook up directly to the progress handler and show a progress bar/spinner to your users from there, like so:
```objc
options.networkAccessAllowed = YES;
options.progressHandler = ^(double progress, NSError *error, BOOL *stop, NSDictionary *info)
{
    ...
};
```

**Comment by chiunam** [comment]
@Dids I have thought about making the picker to download the assets but it looks like creating another system Photos.app. I'm afraid I cannot have such more spare time.

Though the Photos framework supersedes the Assets Library framework, It still looks primitive to me. Take the mentioned `progressHandler` as example, it only workable for iCloud photo library. If the photos are shared via shared PhotoStreams, it will never be called.

**Comment by Sesadev** [comment]
@Dids i am facing the same problem. The videos which is older than 1 week, i am not getting the asset url, please guide me.

**Comment by Sesadev** [comment]
@Dids , i am facing the same issue in iPhone 6 or later, if the video have been added before 1 week. Please Guide me .

**Comment by Dids** [comment]
@Sesadev First I use CTAssetsPickerController to request for assets, which returns an array of them.
Then, when one or more assets have been selected, I run them through a processing function that makes sure they're downloaded, here's a straight up copy & paste from one of my apps:

``` objective-c
- (void)processAssets:(NSArray*)assets
{
    if (!assets || assets.count <= 0) return;

    if (self.cancelling) self.cancelling = NO;

    [SVProgressHUD show];

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        // Start processing all assets (they're automatically queued up)
        __block float delay = 0;
        __block int assetsLeft = (int)assets.count;
        for (PHAsset *asset in assets)
        {
            if (asset)
            {
                PHVideoRequestOptions *options = [[PHVideoRequestOptions alloc] init];
                options.version = PHVideoRequestOptionsVersionOriginal;
                options.networkAccessAllowed = YES;
                options.progressHandler = ^(double progress, NSError *error, BOOL *stop, NSDictionary *info)
                {
                    if (self.cancelling)
                    {
                        //CLS_LOG(@"Cancelling download");
                        *stop = YES;
                        return;
                    }

                    // Show progress with SVProgressHUD
                    dispatch_async(dispatch_get_main_queue(), ^ {
                        [SVProgressHUD showProgress:progress];
                    });
                    //CLS_LOG(@"Downloading video: %f", progress);
                };
                [[PHImageManager defaultManager] requestAVAssetForVideo:asset options:options resultHandler:^(AVAsset *asset, AVAudioMix *audioMix, NSDictionary *info)
                 {
                     assetsLeft--;

                     if (assetsLeft <= 0)
                     {
                         //CLS_LOG(@"All assets downloaded, dismissing progress hud");
                         dispatch_async(dispatch_get_main_queue(), ^ {
                             [SVProgressHUD dismiss];
                         });
                     }

                     if ([asset isKindOfClass:[AVURLAsset class]] || [asset isKindOfClass:[AVAsset class]])
                     {
                         dispatch_after(dispatch_time(DISPATCH_TIME_NOW, delay * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
                             [self startProcessingWithAssetUrl:[(AVURLAsset*)asset URL]];
                         });
                     }
                     else if (!self.cancelling) [self showErrorString:@"An error occurred with the video.\nPlease try again!" report:YES];
                 }];
            }
            else if (!self.cancelling) [self showErrorString:@"An error occurred with the video.\nPlease try again!" report:YES];

            delay += 0.1;
        }
    });
}
```

**Comment by Akhrameev** [comment]
@Dids This code
`if ([asset isKindOfClass:[AVURLAsset class]] || [asset isKindOfClass:[AVAsset class]])
  {
      dispatch_after(dispatch_time(DISPATCH_TIME_NOW, delay * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
           [self startProcessingWithAssetUrl:[(AVURLAsset*)asset URL]];
       });
}`
will fail with slow-motion videos. They are instances of AVAsset (the second class comparison will be called), but not AVURLAsset (have no URL method without custom categories).

Really strange class comparison, cause AVURLAsset is subclass of AVAsset.

**Comment by jagdev7dayz** [comment]
does anybody get solution for it, I am facing same issues ?

**Comment by AnandPGautam** [comment]
Can anyone has found any solution, I am facing the same issue even after setting up the `networkAccessAllowed`?

**Comment by danya61** [comment]
@Dids  I saw implementation of some App where it's started the AVPlayerViewController without waiting for the download complete (from iCloud), and AVPlayerViewController itself controlled the video download process. Don't you know how to implement this?
