### ISSUE TITLE
defaultAssetCollection should be of type PHAssetCollection

### ISSUE THREAD

**Issue by kkarayannis** [chiunam/CTAssetsPickerController#144]
Currently it's: `@property (nonatomic, assign) PHAssetCollectionSubtype defaultAssetCollection;`

**Comment by chiunam** [comment]
There are only 3 possible values of `PHAssetCollectionType` which is not effective for setting `defaultAssetCollection`. Using `PHAssetCollectionSubtype` is more connivence, especially for those who typically want to make the Camera Roll as default.
