### ISSUE TITLE
CTAssetsPickerController run in ios < 8

### ISSUE THREAD

**Issue by ishrek** [chiunam/CTAssetsPickerController#145]
i want run CTAssetsPickerController in ios 7 , How do ???

**Comment by chiunam** [comment]
Use v2.x.x but it is now under minimum maintenance.
https://github.com/chiunam/CTAssetsPickerController/tree/2.x.x

**Comment by mfarhand** [comment]
i am using CTAssetsPickerController & my app support ios 7 also
i want to get last version.
can i use version 2.x.x for iOS 7 & last version for iOS > 7 ? 
please help me

**Comment by chiunam** [comment]
@mfarhand I don't think it works without modification as both version shares common class names. You might fork the v2, modify as you wish and make it works on iOS 7. For iOS > 7, you can keep using v3.
