### ISSUE TITLE
osx 10.11  dyld: Library not loaded: @rpath/CTAssetsPickerController.framework/CTAssetsPickerController

### ISSUE THREAD

**Issue by cczufish** [chiunam/CTAssetsPickerController#147]
dyld: Library not loaded: @rpath/CTAssetsPickerController.framework/CTAssetsPickerController
  Referenced from: /private/var/mobile/Containers/Bundle/Application/9E241461-4D4F-4447-8665-82B9A9826C4C/ios.app/fp_ios
  Reason: no suitable image found.  Did find:
	/private/var/mobile/Containers/Bundle/Application/9E241461-4D4F-4447-8665-82B9A9826C4C/ios.app/Frameworks/CTAssetsPickerController.framework/CTAssetsPickerController: mach-o, but wrong architecture
	/private/var/mobile/Containers/Bundle/Application/9E241461-4D4F-4447-8665-82B9A9826C4C/ios.app/Frameworks/CTAssetsPickerController.framework/CTAssetsPickerController: mach-o, but wrong architecture
	/private/var/mobile/Containers/Bundle/Application/9E241461-4D4F-4447-8665-82B9A9826C4C/ios.app/Frameworks/CTAssetsPickerController.framework/CTAssetsPickerController: mach-o, but wrong architecture

**Comment by chiunam** [comment]
@cczufish A descriptive message of your issue would be more helpful.
