### ISSUE TITLE
Set title count PhotoSelected

### ISSUE THREAD

**Issue by ishrek** [chiunam/CTAssetsPickerController#149]
Hey Guy

i want reload title count of photo selected when : 
Step 1 : Selected 3 Photo - ( Display :  3 photo selected - title : 3 photos selected  - before delete photo)
Step 2 : Click Home Button > Choose Photo My Iphone > delete 1 in 3 photo select of step 1. 
Step 3 : Choose My App Photo : photo deleted in step 2 removed in gridview but title display  3 photo selected - ( Display :  2 photo selected - title : 3 photos selected  - after deleted photo) "ERROR :  PHOTO DELETED BUT TITLE COUNT PHOTO SELECT NOT RELOAD"

Please, Help me

**Comment by chiunam** [comment]
Hi @ishrek, this issue will be fixed in next release.

**Comment by ishrek** [comment]
thanks @chiunam . i'm waiting..... hope as soon as possible
