### ISSUE TITLE
Image blur in picking view controller

### ISSUE THREAD

**Issue by yuchaozh** [chiunam/CTAssetsPickerController#153]
Hi,

I am running your library in IOS 9, but I found the images in the picking controller and the cover for album are blur. Does other has the same issue? Do you know how to fix this?

Thanks.

**Comment by chiunam** [comment]
Hi @yuchaozh, do you have any screenshots provide?

**Comment by scharli** [comment]
One iOS library other this library

![img_0316](https://cloud.githubusercontent.com/assets/3204743/10117127/f03c91cc-644c-11e5-96fc-7e27b5ba214a.PNG)
![img_0315](https://cloud.githubusercontent.com/assets/3204743/10117128/f03d3dca-644c-11e5-949a-1ff64914bff5.PNG)

**Comment by scharli** [comment]
I think that asset.thumbnail in CTAssetsViewCell is returning a small image than in iOS 8

**Comment by chiunam** [comment]
@scharli, I believe the screenshot is come from v2 which use ALAsset framework. Please update to v3.

**Comment by scharli** [comment]
Yes, i update shortly, thanks!

**Comment by yuchaozh** [comment]
Hi @chiunam , I am trying to update the this library. I am running the demo provide by you. But I cannot compile it. The error is as following: 
![cta - error](https://cloud.githubusercontent.com/assets/3889738/10325336/318fa072-6c56-11e5-8e83-d38ae8d63d35.png)
Do you know how to fix this?

Thanks a lot.

**Comment by yuchaozh** [comment]
![thumb_img_1030_1024](https://cloud.githubusercontent.com/assets/3889738/10325532/d4f228c4-6c57-11e5-9d2d-464315527cc2.jpg)
here is the error image

**Comment by chiunam** [comment]
@yuchaozh, might I know your Xcode & SDK versions?

**Comment by yuchaozh** [comment]
Xcode version: 6.3.2
SDK: IOS 8.3

Oh, By the way, The image picker library did not show all the images and videos. For example, in real device the "all photos" I have 1678 photos and 820 videos. But in the library the "all photos" only show 32 photos and 6 videos. Do you know the reason why?

**Comment by yuchaozh** [comment]
I updated my xcode and enable to run the V3 demo now! Nice, the new version shows all photos and videos under the "all photos" category. However, there is no check mark for selected photos. You disabled this feature?

**Comment by chiunam** [comment]
@yuchaozh it was my mistake in last update; added new album types that only available in iOS 9 SDK so it throws error in Xcode 6. Given that Xcode 7 and iOS 9 SDK can built app for iOS 8.1 or above, this error won't be fixed at this moment.

Re the checkmark image, it was included in the library, you might need to run the `pod install` as mentioned in [wiki](https://github.com/chiunam/CTAssetsPickerController/wiki/Running-demo-app).

**Comment by yuchaozh** [comment]
Thanks a lot. The no check mark issue happens in the library demo for "simple use", but when I use the library in my application there is no such error. I am using your library perfectly. Thanks.

**Comment by chiunam** [comment]
@yuchaozh Okay. Issue closed.
