### ISSUE TITLE
delegate didFinishPickingAssets did not return `PHAsset`

### ISSUE THREAD

**Issue by cuzv** [chiunam/CTAssetsPickerController#155]
Weird, in my project, when did finished select image, I get an array contains all  `ALAsset`, not `PHAsset`
How could be like this ?

```
Printing description of assets:
<__NSArrayM 0x7fb8ae2d6ef0>(
ALAsset - Type:Photo, URLs:assets-library://asset/asset.JPG?id=583FF079-AC52-4204-9001-8EFD19833443&ext=JPG
)
```

**Comment by chiunam** [comment]
Please update to v3

**Comment by cuzv** [comment]
@chiunam Thanks, it did work!

**Comment by Jottae** [comment]
Just updated to the latest CTAssetsPickerController (3.3.1).
I have this: 
`func assetsPickerController(_ picker: CTAssetsPickerController!, shouldSelect asset: PHAsset!) -> Bool { print("shouldSelect \(asset.description)") 
return true
}`

And i get this :  `Optional(<__NSArrayM 0x15161d920>(
ALAsset - Type:Photo, URLs:assets-library://asset/asset.JPG?id=B9FC0379-4CFC-41A5-AF2C-D37360A9A7C1&ext=JPG
)
)`

On didFinishPickingAssets i get the Array of ALAsset.
And this is after i have updated through pods.
In my Bridging-Header.h file i have 
`#import "CTAssetsPickerController/CTAssetsPickerController.h"`
I am running on Xcode 8.1 deployment target 8
So why i am not getting a PHAsset objects?
