### ISSUE TITLE
Crash when tick to row folder no content image (Image = 0)

### ISSUE THREAD

**Issue by ishrek** [chiunam/CTAssetsPickerController#156]
hey @chiunam 

when i'm tick to folder no content image  in Ip6+ ios 8.0.2 => crash app

i'm debugging , discovered crash in method "- (void)setupViews" in CTAssetsPickerNoAssetsView 

Please help me

**Comment by chiunam** [comment]
@ishrek,

I don't have iOS 8.0. I have test in the simulator with iOS 8.1 and found no issue. Would you please provide more details?
