### ISSUE TITLE
Conflicting return type in implementation of 'supportedInterfaceOrientations'

### ISSUE THREAD

**Issue by micap** [chiunam/CTAssetsPickerController#157]
in xcode 7 (ios9 sdk) supportedInterfaceOrientations return type is `UIInterfaceOrientationMask` instead of `NSUInteger`. In CTAssetsGroupViewController.m line 106.

**Comment by chiunam** [comment]
Thanks @micap, if you use iOS 9 SDK, it is recommended to update the picker v3. v2 is obsolete.
