### ISSUE TITLE
picker.defaultAssetCollection not working on iPad with form sheet presentation style

### ISSUE THREAD

**Issue by armandzwan** [chiunam/CTAssetsPickerController#160]
picker.defaultAssetCollection = PHAssetCollectionSubtypeSmartAlbumUserLibrary;

Is not working for me, I'm getting a black popup (with empty navbar)

Tried different types, but only PHAssetCollectionSubtypeAlbumRegular gives me a working picker. But then the user has to tap an album first. This is not what I want.

What am I doing wrong?

![screen shot 2015-10-07 at 10 57 34](https://cloud.githubusercontent.com/assets/7809728/10333141/3a267bf2-6ce2-11e5-9fba-3f8ae317a3a5.png)

**Comment by chiunam** [comment]
Hi @armandzwan, the navigation bar is much thicker than an normal iPad app in your screenshot. It seems that your app was developed as an iPhone only app and run it in the 2x zoom view of iPad? It might be the reason as the picker use iOS 8's size class which Apple suggested for building universal apps.

Please try the demo app see whether it works fine. Thanks.

**Comment by armandzwan** [comment]
No it is not. It is an iPad App with just a big Navigation Bar.

**Comment by armandzwan** [comment]
Hi,

It is still not working. Can you reopen this?

**Comment by chiunam** [comment]
Hi @armandzwan, confirmed that this issue only happens on iPad with form sheet presentation style. Will fix it.

**Comment by armandzwan** [comment]
Thanks!

**Comment by chiunam** [comment]
@armandzwan Please update to v3.3.1.

**Comment by armandzwan** [comment]
Sorry, forgot to inform you it is fixed!
