### ISSUE TITLE
"Done" not calling didFinishPickingAssets on iPad when in Album subview

### ISSUE THREAD

**Issue by fastrde** [chiunam/CTAssetsPickerController#163]
When i select an image and click the "Done" button didFinishPickingAssets is not called when I in an album. When I go back to the main view where i can select the albums "Done" fires correctly. On iPhone "Done" fires correctly everywhere.
I use the code in Readme.md "Usages"-section to show the picker.

**Comment by chiunam** [comment]
@fastrde Would you please check with the [demo app](https://github.com/chiunam/CTAssetsPickerController/wiki/Running-demo-app) and see whether it happens?

**Comment by fastrde** [comment]
The demo app is working properly. So it's no general problem with the lib. Maybe something with the example code in the Readme.md or with my implementation of that code.

**Comment by chiunam** [comment]
@fastrde I consider this issue is closed then.
