### ISSUE TITLE
Localize for Swedish (Translation Provided)

### ISSUE THREAD

**Issue by varun531** [chiunam/CTAssetsPickerController#164]
I actually went ahead and paid for the Strings file to be translated into Swedish. Any chance you could create a new CocoaPods version quickly that supports Swedish? Thanks!

(I pasted the contents of the Swedish strings file below, but I can also email it to you if you want.)

/* Navigation bar buttons */
"Cancel" = "Avbryt";
"Done" = "Klar";

/* Default title */
"Photos" = "Foton";

/* No. of selected */
"%@ Photo Selected" = "%@ foto valt";
"%@ Photos Selected" = "%@ foton valda";
"%@ Video Selected" = "%@ video vald";
"%@ Videos Selected" = "%@ videor valda";
"%@ Items Selected" = "%@ artiklar valda";

/* Grid view footer */
"%@ Photos" = "%@ foton";
"%@ Videos" = "%@ videor";
"%@ Photos, %@ Videos" = "%1$@ foton, %2$@ videor";

/* Assets index */
"%@ of %@" = "%1$@ av %2$@";

/* Messages if privacy is not granted */
"This app does not have access to your photos or videos." = "Denna app har inte tillgång till dina foton eller videor.";
"You can enable access in Privacy Settings." = "Du kan aktivera tillgång i Integritetsinställningarna.";

/* Messages if no assets */
"No Photos or Videos" = "Inga foton eller videor";

/* The parameter will be replaced by the device model name */
"You can take photos and videos using the camera, or sync photos and videos onto your %@\nusing iTunes." = "Du kan ta foton och videor med kameran, eller synka foton och videor in i din %@ med hjälp av iTunes.";
"You can sync photos and videos onto your %@ using iTunes." = "Du kan synka foton och videor in i din %@ med hjälp av iTunes.";

/* Accessibility labels */
"Play" = "Spela upp";

/* Video duration spell out */
"hours" = "timmar";
"hour" = "timme";
"minutes" = "minuter";
"minute" = "minut";
"seconds" = "sekunder";
"second" = "sekund";

/* Error message of playing stream video */
"Cannot Play Stream Video" = "Kan inte spela upp video";
"OK" = "OK";

**Comment by chiunam** [comment]
@varun531 You better provide a pull request. I have updated the pod though.
