### ISSUE TITLE
Unrecognized Selector when using Swift

### ISSUE THREAD

**Issue by Akcbryant** [chiunam/CTAssetsPickerController#165]
When I set showSelectionIndex on an instance of CTAssetsPickerController I get the following: `[CTAssetsPickerController setShowsSelectionIndex:]: unrecognized selector sent to instance`

I can replicate this with a fresh single page application with a Podfile that contains the following:

*use_frameworks!*

*pod 'CTAssetsPickerController'`*

**Comment by Akcbryant** [comment]
`picker.showsSelectionIndex = true` works if I go through the manual installation steps so this is probably a cocoapods issue

**Comment by chiunam** [comment]
Hi @Akcbryant, I made a fresh project and cannot reproduce such error. Please make sure the cocoapods install the proper version (3.1.0). 

The result of running `pod install` should look like this:-

````bash
pod install                                                             
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing CTAssetsPickerController (3.1.0)
Installing PureLayout (3.0.1)
Generating Pods project
Integrating client project
````

**Comment by Akcbryant** [comment]
I get the exact same output from running `pod install`.  I am using Swift with Xcode 7.0.1. When I debug into the instance of CTAssetsPickerController it doesn't show that there is a property `showsSelectionIndex` even though I can clearly see it in the source code.  If you have it working in Swift then I must have an issue with cocoapods.

**Comment by Akcbryant** [comment]
Yeah everything is up to date. The Objective-C works flawlessly but using Swift I get this error. Ill update this when if I find out whats wrong.

**Comment by Akcbryant** [comment]
@chiunam Have you run the demo app on a device? I get the same unrecognized selector error when I try to access the "Show selection order" part of the demo.

**Comment by Akcbryant** [comment]
@chiunam Have you tried the demo on a device? I get the same error using the demo app

**Comment by Akcbryant** [comment]
Sorry finger slipped.

**Comment by chiunam** [comment]
@Akcbryant I tried running fresh cloned demo app with Xcode 7.1 and iPhone 6. Still cannot reproduce your issue.

**Comment by Akcbryant** [comment]
Just to be clear, this is on your iPhone 6 device? Not the simulator?

**Comment by chiunam** [comment]
Yes. This is on my iPhone 6 device.
