### ISSUE TITLE
Photos screen refresh issue 

### ISSUE THREAD

**Issue by cashish** [chiunam/CTAssetsPickerController#171]
![screen shot 2015-11-03 at 5 47 00 pm](https://cloud.githubusercontent.com/assets/3477870/10907747/ecc7cf74-8252-11e5-82f3-4352b595641b.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/3477870/10907767/0ec8c380-8253-11e5-8533-359341ba9d41.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/3477870/10907772/132d30e6-8253-11e5-80fe-c898433c0f1c.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/3477870/10907776/18e4d94e-8253-11e5-8b45-34bb1e384e80.png)
All the photos are not shown until there is an interaction with UI.

**Comment by chiunam** [comment]
@cashish From the screenshots, the picker version is 2.x.x. You better update the picker to version 3.x.x and present it in the ordinary way instead of using `UIPopoverController`

**Comment by cashish** [comment]
I have used  UIModalPresentationFormSheet  , is it going to create any issue?

**Comment by chiunam** [comment]
@cashish The demo app also use UIModalPresentationFormSheet. Do you find the same issue?

**Comment by cashish** [comment]
With the new version 3.x.x , my issue is resolved. Thanks a lot for guidance.

**Comment by chiunam** [comment]
@cashish That's good.
