### ISSUE TITLE
Error when build for device(not Simulator)

### ISSUE THREAD

**Issue by EggmanQi** [chiunam/CTAssetsPickerController#185]
```javascript
dyld`dyld_fatal_error:
->  0x12000d088 <+0>: brk    #0x3
```

dyld: Library not loaded: @rpath/Pods.framework/Pods
  Referenced from: /var/mobile/Containers/Bundle/Application/A741FA53-2420-42BF-84A7-EAE546ADDBCC/CTAssetsPickerDemo.app/CTAssetsPickerDemo
  Reason: image not found

---
Try ![solution](http://img2.tuicool.com/aIJnAf.jpg)
Not work

**Comment by EggmanQi** [comment]
Solution：
http://stackoverflow.com/questions/29126835/swift-framework-depending-on-cocoa-pod/29463810#29463810

**Comment by chiunam** [comment]
@EggmanQi I am not quite understand the issue. It seems to me that it is issue of Cocoapods or project settings.
