### ISSUE TITLE
use PHImageManager requestImageForAsset method can't get origin image from cloud

### ISSUE THREAD

**Issue by qylibohao** [chiunam/CTAssetsPickerController#190]
i use the phimagemager to request the image form cloud, the request options is below:
    self.requestOptions = [[PHImageRequestOptions alloc] init];
    self.requestOptions.version = PHImageRequestOptionsVersionCurrent;
    self.requestOptions.resizeMode   = PHImageRequestOptionsResizeModeFast;
    self.requestOptions.deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic;
    self.requestOptions.networkAccessAllowed = YES;
    self.requestOptions.synchronous = YES;

        [manager requestImageForAsset:asset
                           targetSize:PHImageManagerMaximumSize
                          contentMode:PHImageContentModeAspectFill
                              options:self.requestOptions
                        resultHandler:^void(UIImage *image, NSDictionary *info) {

                        }
but the result handler block always return nil image .why??

**Comment by mythodeia** [comment]
'''PHImageRequestOptionsDeliveryModeOpportunistic''' might call the completion handler more than once. In your case it returns nil every single time or does it show a degraded image first and then nil?

**Comment by chrisze** [comment]
Try `self.requestOptions.synchronous = NO;`

**Comment by chiunam** [comment]
@qylibohao Please check the documentation of `PHImageManger`
