### ISSUE TITLE
GestureRecognizer pop problem

### ISSUE THREAD

**Issue by bawn** [chiunam/CTAssetsPickerController#193]
![image](http://i12.tietuku.com/038c4bac7655cb34.gif)

**Comment by chiunam** [comment]
Hi @bawn, I don't understand what's the issue you were referring to. I can use the pop gesture smoothly in my iPhone. Could you please elaborate?

**Comment by bawn** [comment]
@chiunam sorry, I should not clearly described

Step 1: Enter the group page
Step 2: Click on any one cell enter the album
Step 3: Click back item back to group page
Step 4: From the left to the right edge of the screen slide
Step 5: Click on any one cell, This will not push other page

**Comment by chiunam** [comment]
@bawn Got it. Thanks.
