### ISSUE TITLE
the demo couldn't release memory

### ISSUE THREAD

**Issue by 515783034** [chiunam/CTAssetsPickerController#195]
when i run the demo app,it's memory grow up but it never back when i dismiss viewController.
is there something wrong?

**Comment by chiunam** [comment]
@515783034 I am going to merge a PR that could fix memory issue. Please refer to the discussion in issue #189.

**Comment by chiunam** [comment]
@515783034 Please test v3.2.2 and see if it reduces memory usage. Thanks.
