### ISSUE TITLE
Can't enable only photos (without videos)

### ISSUE THREAD

**Issue by MonsWriter** [chiunam/CTAssetsPickerController#196]
picker.assetsFilter = [ALAssetsFilter allPhotos]
This method from CocoaDocs doesn't work.

-(BOOL)assetsPickerController:(CTAssetsPickerController *)picker shouldEnableAssetForSelection:(ALAsset *)asset
And this method doesn't work too.

How can I pick only photos with CTAssetsPickerController?

**Comment by chiunam** [comment]
@MonsWriter There are no support to version 2.x.x. Please upgrade to latest version (v3) and refer to the demo app.
