### ISSUE TITLE
Crashing the App on Selecting Albums 

### ISSUE THREAD

**Issue by Deepak-Nair** [chiunam/CTAssetsPickerController#197]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'

libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by nagainfosolutions** [comment]
I am also getting this crash. It seems the CTAssetsPickerController.bundle is not being created.
I am using cocoa pods.

**Comment by chiunam** [comment]
Hi @Deepak-Nair and @nagainfosolutions, may I know which version of cocoapods you used? There is another issue related missing localisation files and images, which the pods were built from a pre-release version of Cocoapods.
