### ISSUE TITLE
Appearance Proxy doesn't change Navbar title color

### ISSUE THREAD

**Issue by ctews** [chiunam/CTAssetsPickerController#198]
Hey guys,

I'm just stuck with the appearance proxy and it is also not working in the demo example so I'm wondering what is going wrong here. I'm trying to change the UINavigationBar title attributes like following:

```
let navBar = UINavigationBar.appearanceWhenContainedInInstancesOfClasses([CTAssetsPickerController.self])
 navBar.titleTextAttributes = [NSForegroundColorAttributeName:UIColor.whiteColor()]
```

but the color doesn't get applied Tintcolor for example works (also in example app) but title color refused to work. Any suggestions? Calling it at the same time like in the `CTAppearanceViewController` example.

Thanks in advance!

**Comment by chiunam** [comment]
Hi @ctews, last release (v3.2.2) broke the navigation bar proxy. If you urgently need this feature, please try v3.2.1.

**Comment by ctews** [comment]
Thx very much for the quick fix @chiunam!
