### ISSUE TITLE
相机胶卷照片为空时不显示相册

### ISSUE THREAD

**Issue by cooerson** [chiunam/CTAssetsPickerController#200]
1.相机胶卷没有照片时，显示没有照片，但其实其它相册是有照片的。

**Comment by chiunam** [comment]
其他相冊指的是甚麼相冊？以我所知在 iPhone 建立相冊的相均來自相機膠卷 (Camera Roll) 的。

**Comment by cooerson** [comment]
比如在mac上新建的相册，同步到iphone上的：
![img_9414](https://cloud.githubusercontent.com/assets/290716/12410066/119fcb04-beac-11e5-9b0e-96005d135c9e.PNG)

**Comment by chiunam** [comment]
Hi @cooerson, Photos framework 預設不包括經由 iTunes Sync 到 iPhones 的相簿，如你的 app 是 iOS 9 only，你可先建立 `PHFetchOptions`，並把 [`TypeiTunesSynced`](https://developer.apple.com/library/prerelease/ios/documentation/Photos/Reference/PHAsset_Class/index.html#//apple_ref/swift/struct/c:@E@PHAssetSourceType) 加到 [`includeAssetSourceTypes`](https://developer.apple.com/library/prerelease/ios/documentation/Photos/Reference/PHFetchOptions_Class/index.html#//apple_ref/occ/instp/PHFetchOptions/includeAssetSourceTypes) property，再 assign 到 picker 的 `assetCollectionFetchOptions` 及 `assetsFetchOptions`，就可顯示那些相簿。

**Comment by cooerson** [comment]
主要是感觉这部分的行为跟系统的picker略有差异：）

**Comment by chiunam** [comment]
在我看來 Photos framework 仍很粗糙，還有很多限制，而系統的 picker 應不是用 Photos framework，所以不能避免差異。
