### ISSUE TITLE
国际化和图标等若干小问题

### ISSUE THREAD

**Issue by cooerson** [chiunam/CTAssetsPickerController#201]
1.国际化仍然是英文啊
2.选中的照片没有打勾的图标
3.showsEmptyAlbums = no 不起作用

picker.showsEmptyAlbums = NO;
picker.showsNumberOfAssets = YES;
picker.showsCancelButton = YES;
picker.showsSelectionIndex = YES;
picker.alwaysEnableDoneButton = YES;

![img_9412](https://cloud.githubusercontent.com/assets/290716/12409295/c219ce70-bea3-11e5-8827-45bf3392fc34.PNG)
![img_9413](https://cloud.githubusercontent.com/assets/290716/12409296/c3d2fe3a-bea3-11e5-81cc-2843e1e007cf.PNG)

**Comment by chiunam** [comment]
更新到最新的版本 (v3) 吧。這個截圖是舊版本 (v2) 的。

**Comment by cooerson** [comment]
pod 'CTAssetsPickerController',  '~> 3.2.0' 的确是用的v3最新的3.2.3

另外，现在demo pod install的时候报错如下
Updating local specs repositories
Analyzing dependencies
[!] The dependency `CTAssetsPickerController (from `./`)` is not used in any concrete target.

**Comment by chiunam** [comment]
應該是 bundle path 有誤令到需要的圖示和 localisation file 不能載入，所以看不到中文及圖示。剛用 Cocoapods v0.39.0 試過還是正確的，不知你是否用 pre-release 版本，可以的話用正式版試試看。

**Comment by cooerson** [comment]
是的，已经解决，多谢

**Comment by chiunam** [comment]
:+1:
