### ISSUE TITLE
fatal: Remote branch v3.2.4 not found in upstream origin

### ISSUE THREAD

**Issue by a9austin** [chiunam/CTAssetsPickerController#207]
I get this error when running pod install.

Installing CTAssetsPickerController (3.2.4)

[!] Error installing CTAssetsPickerController
[!] /usr/bin/git clone https://github.com/chiunam/CTAssetsPickerController.git /var/folders/5g/9jwrd_bs2bd7_wqy8xvg3y_c0000gn/T/d20160121-43823-f9hiay --single-branch --depth 1 --branch v3.2.4

Cloning into '/var/folders/5g/9jwrd_bs2bd7_wqy8xvg3y_c0000gn/T/d20160121-43823-f9hiay'...
warning: Could not find remote branch v3.2.4 to clone.
fatal: Remote branch v3.2.4 not found in upstream origin

**Comment by chiunam** [comment]
@a9austin Sorry, I misdelete the tag in github. It should work now.

**Comment by a9austin** [comment]
It was an issue with my cocoapods.
