### ISSUE TITLE
Could you set maxPickerCount to limit select assets ?

### ISSUE THREAD

**Issue by ihugang** [chiunam/CTAssetsPickerController#208]
I want limit picker photo number, How can I do it ?

**Comment by chiunam** [comment]
Check the demo app and there is an example

**Comment by ihugang** [comment]
for better user experience ，I suggest that setup a limit number, forbid users when they select photo.

**Comment by chiunam** [comment]
Have you really check the [sample code](https://github.com/chiunam/CTAssetsPickerController/blob/master/CTAssetsPickerDemo/Examples/CTMaxSelectionViewController.m)? It does what exactly you are talking about.

**Comment by nileshpol18** [comment]
```
func assetsPickerController(picker: CTAssetsPickerController!, shouldSelectAsset asset: PHAsset!) -> Bool {

        return picker.selectedAssets.count < 5 ? true : false
}
```
