### ISSUE TITLE
Not Able to Hide Videos On Picker

### ISSUE THREAD

**Issue by michaelmaloof** [chiunam/CTAssetsPickerController#212]
I'm fairly new to using other people's frameworks so I apologize for the rookie question. I've looked through the code, questions, and online documentation and still can't find where I'm able to prevent the Picker from showing any videos. I can hide albums of just videos but I can hide all the videos. Please help. Thanks!

**Comment by bridworks** [comment]
CTAssetsPickerController *picker = [[CTAssetsPickerController alloc] init];
    picker.delegate = self;
    
    NSPredicate *predicateMediaType = [NSPredicate predicateWithFormat:@"mediaType = %d",PHAssetMediaTypeImage];
    NSCompoundPredicate *compoundPredicate = [NSCompoundPredicate andPredicateWithSubpredicates:@[predicateMediaType]];
    picker.assetsFetchOptions = [[PHFetchOptions alloc] init];
    picker.assetsFetchOptions.predicate = compoundPredicate;
    
    [self presentViewController:picker animated:YES completion:nil];

**Comment by chiunam** [comment]
@bridworks Thanks!

@michaelmaloof You might also refer to the sample code [`CTPhotosViewController.m`](https://github.com/chiunam/CTAssetsPickerController/blob/master/CTAssetsPickerDemo/Examples/CTPhotosViewController.m). It does exactly what you are asking.

**Comment by michaelmaloof** [comment]
Wonderful thank you!
