### ISSUE TITLE
Support git submodule

### ISSUE THREAD

**Issue by aries-zhang** [chiunam/CTAssetsPickerController#213]
How about split the framework and demo app? So git submodule can be used, and people can just finish their job by referencing the framework.

By the way, CocoaPod sucks. Many people dislike it making so much changes to their workspace. Please, let them live by adding alternative ways like [Carthage](https://github.com/Carthage/Carthage).

**Comment by chiunam** [comment]
Hi @aries-zhang, submodule should still works. Please refer to [wiki](https://github.com/chiunam/CTAssetsPickerController/wiki/Manual-Setup-(v3)) on setting up your project manually. 

Thanks for letting me know about Carthage btw. As I'm rather new to it and too busy to learn about it. If you have idea of adding Carthage support in this picker, please send a PR. Thanks.
