### ISSUE TITLE
Prevent the picker from showing photo's app 'Hidden' album.

### ISSUE THREAD

**Issue by keronakhla** [chiunam/CTAssetsPickerController#223]
I'm new to using this framework so I apologize if my question has been answered before. I've looked through the code, questions, and the documentation and still can't find where I'm able to prevent the Picker from not showing the 'Hidden' photo album that some users may have. I don't want the 'Hidden' album to show if the user has one.

**Comment by chiunam** [comment]
@keronakhla You can create an array of asset collection subtype and assign it to [`assetCollectionSubtypes`](http://cocoadocs.org/docsets/CTAssetsPickerController/3.3.1/Classes/CTAssetsPickerController.html#//api/name/assetCollectionSubtypes)
