### ISSUE TITLE
navigationbar wont change

### ISSUE THREAD

**Issue by Fredehagelund92** [chiunam/CTAssetsPickerController#46]
What ever i do i cant seem to change the navigation bar color?

Where do i need to put the code for that?

**Comment by carl1990** [comment]
I has do this:
`picker.navigationController.navigationBar.backgroundColor = [UIColor whiteColor];` `picker.navigationController.navigationBar.tintColor = [UIColor whiteColor];`
`picker.navigationController.navigationBar.translucent = NO;`

but it is navigationBar is also translucent

**Comment by ionutsebastian824** [comment]
it's not working

**Comment by z563721** [comment]
No working and the navigationController property is nil or 0x000000000
