### ISSUE TITLE
Feature request: add AirPlay picker

### ISSUE THREAD

**Issue by jamiebullock** [chiunam/CTAssetsPickerController#50]
It would be great if the CTAssetScrollView contained an AirPlay picker.

I believe this should be fairly easy to add with an [MPVolumeView](https://developer.apple.com/library/ios/documentation/AudioVideo/Conceptual/AirPlayGuide/EnrichYourAppforAirPlay/EnrichYourAppforAirPlay.html)

I tried hacking in one myself, but I was certain of the best approach in keeping with your architecture.

**Comment by chiunam** [comment]
This request probably won't be implemented in the near future.
