### ISSUE TITLE
Warning when building pod project

### ISSUE THREAD

**Issue by sadiq81** [chiunam/CTAssetsPickerController#79]
/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerLocked.imageset/[][][][][][UIAccessDeniedViewLock.png]
Warning:The image set "CTAssetsPickerLocked" has 3 unassigned images.

/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerPlay.imageset/[][][][][][CTAssetsPickerPlay.png]
Warning:The image set "CTAssetsPickerPlay" has 3 unassigned images.

/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerChecked.imageset/[][][][][][CTAssetsPickerChecked.png]
Warning:The image set "CTAssetsPickerChecked" has 3 unassigned images.

/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerVideo.imageset/[][][][][][CTAssetsPickerVideo.png]
Warning:The image set "CTAssetsPickerVideo" has 3 unassigned images.

/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerEmptyCell.imageset/[][][][][][CTAssetsPickerEmptyCell.png]
Warning:The image set "CTAssetsPickerEmptyCell" has 3 unassigned images.

/Users/privat/iOS/HalalGuide/Pods/CTAssetsPickerController/CTAssetsPickerController/CTAssetsPicker.xcassets:./CTAssetsPickerEmptyAsset.imageset/[][][][][][CTAssetsPickerEmptyAsset.png]
Warning:The image set "CTAssetsPickerEmptyAsset" has 3 unassigned images.

**Comment by chiunam** [comment]
Hi @sadiq81. The podspec has been update. Please test again with the latest Podfile:-

````
pod 'CTAssetsPickerController',  '~> 2.9.0'
````

**Comment by chiunam** [comment]
Closed due to inactivity.
