### ISSUE TITLE
Video Quality is very low.

### ISSUE THREAD

**Issue by fustalol** [chiunam/CTAssetsPickerController#84]
With default settings, picking a video from gallery result is very very low.
How can I take the native video on gallery?

**Comment by chiunam** [comment]
@fustalol You should get the native video by passing `AVAssetExportPresetPassthrough` value in `exportSessionWithAsset:presetName:` method. Please refer to [Apples's documentation](https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVAssetExportSession_Class/index.html#//apple_ref/occ/clm/AVAssetExportSession/exportSessionWithAsset:presetName:) for other possible values.
