### ISSUE TITLE
No "swipe to go back" gesture

### ISSUE THREAD

**Issue by duc1701** [chiunam/CTAssetsPickerController#85]
The iOS7-style "swipe to go back" gesture doesn't seem to work in the thumbnail view. I'm fairly new to iOS development so I might be missing something obvious, but it doesn't seem like you're disabling backBarButtonItem or anything, so I'm confused as to why it's not working. 

Thanks for all the great work you've done! I'm looking forward to the PhotoKit version.

**Comment by chiunam** [comment]
@duc1701 Thanks for report. It has been fixed on the latest version. The PhotoKit version is now on hold as I do not have much time to do so.
