### ISSUE TITLE
The demo build failed.

### ISSUE THREAD

**Issue by Easence** [chiunam/CTAssetsPickerController#86]
Hi,the demo cannot build success.
The error below:
 rsync: link_stat "/CTAssetsPickerController-master/Pods/${BUILT_PRODUCTS_DIR}/CTAssetsPickerController.bundle" failed: No such file or directory (2)
done
sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

**Comment by chiunam** [comment]
Hi @Easence,
Starting from version 2.9.0, this control requires building from cocoapods. Please see [readme](https://github.com/chiunam/CTAssetsPickerController#running-the-demo-app) for the details.
