### ISSUE TITLE
cannot see CTAssetsPickerLocked  in XCode 6.1

### ISSUE THREAD

**Issue by lawrsp** [chiunam/CTAssetsPickerController#87]
XCode 6.1 ， develop target 7.1， run on ios8.1， 
cannot see the lock image

I found the file in xcode is UIAccessDeniedViewLock，so I change the code， and the image appears correctly。

Maybe the name mistakes？ or the ImageSet cannot  be recognized in XCode 6.1 ？

**Comment by chiunam** [comment]
@lawrsp Yes. The images were named mistakenly
