### ISSUE TITLE
Slow Motion Videos with Crash in Preview

### ISSUE THREAD

**Issue by drchris1502** [chiunam/CTAssetsPickerController#88]
I'm having a problem with CTAssetsPickerController that seems to be consistent with videos that utilize the slow motion feature of iOS.  In the device (not the Simulator), the long-press preview causes my app to crash if selecting a slow motion video.  In the Simulator, this does not happen - the preview plays fine. 

Interestingly, in the simulator the length of the video in the GroupViewController is shown as if there is slow motion (longer length) and in the device the length is shown as it there is no slow motion (shorter length).  Also interestingly, in the simulator, the slow motion effect is displayed while in the device it is not.

The main issue here is the crash when long-pressing on a video that utilizes slow motion.

Thanks!
Chris

**Comment by chiunam** [comment]
@drchris1502 To my understanding, the slow motion effect is depends on the video player. The iOS Photos.app plays the higher fps video with 60 fps to achieve such effect. (Indeed, it's more complicated. e.g. you can select which portion of video to be 'slow' in Photos.app.) Such effect requires corresponding APIs to detect, play and adjust the speed etc. I did a quick search and can't find such APIs so I believe it cannot be made at this moment. What you see in simulator might be the differences of the ability to play high fps videos.

Re your crashing issues, would you please test again with the demo app? I tried some slow motion videos recorded in camera roll and they can be played nicely in preview, just without the slow motion effect.

**Comment by chiunam** [comment]
Closed due to inactivity.
