### ISSUE TITLE
Wrong view height or position when sharing internet connection

### ISSUE THREAD

**Issue by tomoyuki28jp** [chiunam/CTAssetsPickerController#91]
Selection count view bottom is not on window bottom when sharing internet connection.

![evernote camera roll 20150226 000837](https://cloud.githubusercontent.com/assets/42951/6373137/4187978c-bd4c-11e4-957b-250925123ab9.png)

**Comment by chiunam** [comment]
@tomoyuki28jp Thanks for reporting.

**Comment by tomoyuki28jp** [comment]
@chiunam Confirmed this issue has been fixed. Thanks!
