### ISSUE TITLE
IOS8 in iCloud in the picture does not show

### ISSUE THREAD

**Issue by jiekewei** [chiunam/CTAssetsPickerController#93]
IOS8 in iCloud in the picture does not show.

**Comment by chiunam** [comment]
@jiekewei Photos in iCloud might not be shown properly if they haven't been downloaded to the device.  It's the limitation of ALAssets framework. Hopefully it can be achieved in the future release by using iOS 8 Photos framework.

**Comment by chiunam** [comment]
Fixed in the [v3.0.0-beta.1](9301ee2df72a3cd75648eef525f11af35623ebe6)

**Comment by summertian4** [comment]
Can CTAssetsPickerController choose the picture in iCloud When picture haven't been downloaded now?

**Comment by chiunam** [comment]
Yes. That should be okay since v3.0.0
