### ISSUE TITLE
bundle path error

### ISSUE THREAD

**Issue by NilStack** [chiunam/CTAssetsPickerController#95]
Hi, @chiunam:
I installed the latest version CTAssetsPickerController with cocoapods and built it successfully, but when
tested it in simulator i got this error. It happened when i clicked the 'Camera Roll' cell in the first view.
  
"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument'"

I think maybe there is something wrong with localization bundle path. So is there something i need to do with the bundle?
other info: Xcode 6.2, iOS 8, "use_frameworks!" in podfile

Thanks for sharing CTAssetsPickerController!

**Comment by chiunam** [comment]
Hi @NilStack, may I know which localisation used in your app?

**Comment by NilStack** [comment]
I don't set locale in my app. The language setting  in the simulator is English and region is United States. 
Sorry i have few experience in localization.

**Comment by chiunam** [comment]
@NilStack okay. That might be the differences between building pods with frameworks and static library. Let me check.

**Comment by NilStack** [comment]
@chiunam Thanks for fixing it.

**Comment by chiunam** [comment]
@NilStack Cool.
