### ISSUE TITLE
[NSPlaceholderString initWithFormat:locale:arguments:]: nil argument' *** First throw call stack:

### ISSUE THREAD

**Issue by AJBeltran3** [chiunam/CTAssetsPickerController#97]
Hello

I just downloaded and added this to my project. 

I am getting the error above. Whenever I show the CTAssestsPickerController and select which folder of pictures I want to go into this error is shown. 

Any ideas on what is happening or how to resolve it?

**Comment by chiunam** [comment]
@AJBeltran3 May I know whether have you localised your app?

**Comment by alexagarkusha** [comment]
@AJBeltran3 I had the same problem. There is problem in founding localization on special bundle. In NSBundle+CTAssetsPickerController.h you can find special define CTAssetsPickerControllerLocalizedString.

**Comment by chiunam** [comment]
@alexagarkusha Thanks for your supplement. I would recommend adding this control by cocoapods. It manages all dependency and builds the bundle automatically. The upcoming major release will only support cocoapods.

If you really need manually manage the dependency, please refer to [SUBMODULES-NOTES](https://github.com/chiunam/CTAssetsPickerController/blob/master/SUBMODULES-NOTES.md) for building the bundle.
