### ISSUE TITLE
Crash on CTAssetsPageViewController.m  (NSRangeException) while monkey test

### ISSUE THREAD

**Issue by samw723** [chiunam/CTAssetsPickerController#98]
Thread : Fatal Exception: NSRangeException
0  CoreFoundation                 0x0000000107b79f1d __exceptionPreprocess + 141
1  libobjc.A.dylib                0x0000000107812bb7 objc_exception_throw + 45
2  CoreFoundation                 0x0000000107a7201e -[__NSArrayI objectAtIndex:] + 190
3  migme                          0x0000000103c91560 -[CTAssetsPageViewController pageIndex] (CTAssetsPageViewController.m:98)
4  migme                          0x0000000103c9df3c -[CTAssetsViewControllerTransition animateTransition:] (CTAssetsViewControllerTransition.m:62)

**Comment by chiunam** [comment]
@samw723 Thanks. More information of the issue could be helpful.

**Comment by chiunam** [comment]
Closed due to inactivity.
